name: Deploy via FTP

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftp
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}

          # destino correto do site
          server-dir: /public_html/

          # somente arquivos do site
          local-dir: ./public_html/

          # ðŸ”¥ IMPORTANTE â€” evita erro 550 da Locaweb
          dangerous-clean-slate: false

          # evita deletar arquivos do servidor
          state-name: .ftp-deploy-sync-state.json

          log-level: verbose

          exclude: |
            **/.git*
            **/.github/**
            **/.env*
            **/*.log
            **/tmp/**
            **/cache/**
            **/uploads/**
            **/node_modules/**
            **/vendor/**
            **/assets/**
            logs/**
